// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommonOutput struct {
	Status  bool    `json:"status"`
	Code    int     `json:"code"`
	Message *string `json:"message"`
}

type SignInInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignInOutput struct {
	Respon *CommonOutput `json:"respon"`
	User   *User         `json:"user"`
}

type User struct {
	ID          int    `json:"id"`
	Username    string `json:"username"`
	Name        string `json:"name"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	Phonenumber string `json:"phonenumber"`
}
